Portfolio top header
AshwinCarvalho999/Portfolio-new pull request #1
Opened 2022-07-07 05:29 UTC by AshwinCarvalho999

2022-07-07 06:17 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp9z2Rq_bAJ42eRNxObBr1nKDUbZjLw2QqkQ&usqp=CAU)

### Hey @AshwinCarvalho999 :wave:

### Highlights :1st_place_medal:

:heavy_check_mark: Following Linters 
:heavy_check_mark: Following GitHub Flow


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

# Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 06:17 UTC, HAMMAS-SALEEM commented on style.css
> +}
- [ ] Please remove these styling to fix the background image. :+1:

2022-07-07 06:17 UTC, HAMMAS-SALEEM commented on index.html
> +          </div>
- [ ] Please add width: 100%; to this image to follow the figma template :+1:

2022-07-07 06:17 UTC, HAMMAS-SALEEM commented on index.html
> +               <a href="#" class="btn-voilet">Start collaboration</a>
- [ ] Please change this `a` tag to a `button` tag to implement the following styling shown below image :+1:
![fix-button](https://user-images.githubusercontent.com/93039359/177703715-c5bd11b6-3afb-463f-b365-456f0ffe5c02.png)

2022-07-07 06:17 UTC, HAMMAS-SALEEM commented on style.css
> +  margin: 1;
- [ ] Please remove this margin: 1; to follow the figma template. :+1:

2022-07-07 06:17 UTC, HAMMAS-SALEEM commented on style.css
> +}
- [ ] Please make your styling for the .menu-icon as shown in the image below to fix your nav icon position :+1:
![nav-icon-styling](https://user-images.githubusercontent.com/93039359/177704642-93de9bdf-5360-4044-a046-b2227f78f2af.png)

2022-07-07 11:22 UTC, codecaiine requested changes
Hi @AshwinCarvalho999 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 11:22 UTC, codecaiine commented on index.html
> +          </div>
- [ ] [REQUIRED] Nice job so far, But As the previous reviewer mentioned [here](https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915485959) you need to put this content inside `section` tag not in `header`.  :+1:

2022-07-07 11:55 UTC, AshwinCarvalho999 commented
Done.

On Thu, Jul 7, 2022, 4:52 PM Yannick-Noel AKA ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @AshwinCarvalho999 <https://github.com/AshwinCarvalho999> ,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Highlights
>
>    - Descriptive Pull request ✔️
>    - Good use of Gitflow ✔️
>    - Commits are meaningful ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.*** <https://github.com/codecaiine>)
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915743082>
> :
>
> > +          <div class="header">Ashwin <br />Carvalho</div>
>
> +          <div class="paragraph">
>
> +               Hello! I am a software developer! I can <br />
>
> +               help you build a product, feature or <br />
>
> +               website. Taka a look of my works.<br />
>
> +               If you like what you see and have a<br />
>
> +               project you need coded, don`t hesitate<br />
>
> +               and contact me.
>
> +          </div>
>
> +          <div class="section">
>
> +               <a href="#" class="button">Start collaboration</a>
>
> +
>
> +               <div class="img-geomery-2">
>
> +                    <img src="images/image_geometry_2.svg" alt="design-geometry" />
>
> +               </div>
>
> +          </div>
>
>
>
>    - [REQUIRED] Nice job so far, But As the previous reviewer mentioned
>    here
>    <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915485959>
>    you need to put this content inside section tag not in header. 👍
>
> ------------------------------
>
> In index.html
> <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915749236>
> :
>
> > +               </nav>
>
> +          </div>
>
> +
>
> +          <div class="header">Ashwin <br />Carvalho</div>
>
> +          <div class="paragraph">
>
> +               Hello! I am a software developer! I can <br />
>
> +               help you build a product, feature or <br />
>
> +               website. Taka a look of my works.<br />
>
> +               If you like what you see and have a<br />
>
> +               project you need coded, don`t hesitate<br />
>
> +               and contact me.
>
> +          </div>
>
> +          <div class="section">
>
> +               <a href="#" class="button">Start collaboration</a>
>
> +
>
> +               <div class="img-geomery-2">
>
>
>
>    - [REQUIRED] As the previous reviewer mentioned here
>    <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915490374>,
>    please use this background in your css style not as img. 😺
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#pullrequestreview-1031384868>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVKQBYTA5A4Y5KMHVB6IZULVS24YZANCNFSM524BRA4A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-07 12:00 UTC, AshwinCarvalho999 commented
He told me to make the width of image to 100% and i done it

On Thu, Jul 7, 2022, 5:25 PM Ashwin Carvalho ***@***.***>
wrote:

> Done.
>
> On Thu, Jul 7, 2022, 4:52 PM Yannick-Noel AKA ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi @AshwinCarvalho999 <https://github.com/AshwinCarvalho999> ,
>>
>> Great work on making the changes requested by a previous reviewer 👏
>> You've done well implementing some of the requested changes, but there
>> are still some which aren't addressed yet.
>> Highlights
>>
>>    - Descriptive Pull request ✔️
>>    - Good use of Gitflow ✔️
>>    - Commits are meaningful ✔️
>>
>> Required Changes ♻️
>>
>> *Check the comments under the review.*
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
>> PR. However, I strongly recommend you to take them into account as they can
>> make your code better. Some of them were simply missed by the previous
>> reviewer and addressing them will really improve your application.*
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me ***@***.*** <https://github.com/codecaiine>)
>> in your question so I can receive the notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>> ------------------------------
>>
>> In index.html
>> <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915743082>
>> :
>>
>> > +          <div class="header">Ashwin <br />Carvalho</div>
>>
>> +          <div class="paragraph">
>>
>> +               Hello! I am a software developer! I can <br />
>>
>> +               help you build a product, feature or <br />
>>
>> +               website. Taka a look of my works.<br />
>>
>> +               If you like what you see and have a<br />
>>
>> +               project you need coded, don`t hesitate<br />
>>
>> +               and contact me.
>>
>> +          </div>
>>
>> +          <div class="section">
>>
>> +               <a href="#" class="button">Start collaboration</a>
>>
>> +
>>
>> +               <div class="img-geomery-2">
>>
>> +                    <img src="images/image_geometry_2.svg" alt="design-geometry" />
>>
>> +               </div>
>>
>> +          </div>
>>
>>
>>
>>    - [REQUIRED] Nice job so far, But As the previous reviewer mentioned
>>    here
>>    <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915485959>
>>    you need to put this content inside section tag not in header. 👍
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915749236>
>> :
>>
>> > +               </nav>
>>
>> +          </div>
>>
>> +
>>
>> +          <div class="header">Ashwin <br />Carvalho</div>
>>
>> +          <div class="paragraph">
>>
>> +               Hello! I am a software developer! I can <br />
>>
>> +               help you build a product, feature or <br />
>>
>> +               website. Taka a look of my works.<br />
>>
>> +               If you like what you see and have a<br />
>>
>> +               project you need coded, don`t hesitate<br />
>>
>> +               and contact me.
>>
>> +          </div>
>>
>> +          <div class="section">
>>
>> +               <a href="#" class="button">Start collaboration</a>
>>
>> +
>>
>> +               <div class="img-geomery-2">
>>
>>
>>
>>    - [REQUIRED] As the previous reviewer mentioned here
>>    <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#discussion_r915490374>,
>>    please use this background in your css style not as img. 😺
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#pullrequestreview-1031384868>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AVKQBYTA5A4Y5KMHVB6IZULVS24YZANCNFSM524BRA4A>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-07-07 13:28 UTC, HAMMAS-SALEEM commented
Brother, you have to add that image as a background through the CSS I have mentioned above you can see in the requirements. Please add it through CSS as a background image :+1:

2022-07-08 10:07 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:

Your project is complete. There is nothing else to say about your project. :+1:
Go ahead and merge it. :muscle:

## Highlights :1st_place_medal:
:heavy_check_mark: Following LInter
:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Following Requirements
:heavy_check_mark: Great Validations

### [Optional]

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! clap clap clap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 10:08 UTC, merged

2022-07-08 10:11 UTC, AshwinCarvalho999 commented
Awesome, thank you so much!

On Fri, Jul 8, 2022, 3:37 PM HAMMAS BIN SALEEM ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Status: Approved 🟢
>
> Your project is complete. There is nothing else to say about your project.
> 👍
> Go ahead and merge it. 💪
> Highlights 🥇
>
> ✔️ Following LInter
> ✔️ Following GitHub Flow
> ✔️ Following Requirements
> ✔️ Great Validations
> [Optional]
>
> *All the changes with optional tags are not crucial enough to prevent you
> from getting the approval but we highly recommend to students that they
> should take these changes into consideration.*
>
> Cheers and Happy coding! clap clap clap
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear. Please, remember to tag me in your question so I can
> receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AshwinCarvalho999/Portfolio-new/pull/1#pullrequestreview-1032697958>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVKQBYVOFUHPPRMA7CUPH43VS74XZANCNFSM524BRA4A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>